project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    
format:
  html:
    embed-resources: false
    theme: none
    page-layout: custom
    include-before-body:
      - layouts/components/announcement.html
      - layouts/components/header.html
      - layouts/components/container-start.html
    include-after-body:
      - layouts/components/container-end.html
      - layouts/components/footer.html
    css: 
      - "style/base/colors.css"
      - "style/base/fonts.css"
      - "style/base/layout.css"
      - "style/base/typography.css"
      - "style/components/blockquote.css"
      - "style/components/breadcrumbs.css"
      - "style/components/buttons.css"
      - "style/components/code.css"
      - "style/components/dropdown.css"
      - "style/components/gallery.css"
      - "style/components/lists.css"
      - "style/components/tables.css"
      - "style/sections/announcement.css"
      - "style/sections/header.css"
      - "style/sections/footer.css"
      - "style/sections/sidebar.css"
